### ISSUE TITLE
Sort announcement cards by date

### ISSUE THREAD

**Issue by sunnyguan** [sunnyguan/whiteboard#10]
Currently announcement cards are sorted by the default order; it would be more helpful if they were sorted by newest to oldest.

**Comment by guptaji048** [comment]
Can i contribute?

**Comment by guptaji048** [comment]
Would like to contribute, please assign it to me

**Comment by guptaji048** [comment]
I dont have utd login ID and password, is there a work around? If not, then unassign me.
