### ISSUE TITLE
Some discussion boards do not display. 

### ISSUE THREAD

**Issue by GaganBhat** [sunnyguan/whiteboard#23]
![image](https://user-images.githubusercontent.com/25236969/100770871-5d300700-33c3-11eb-9e2a-5e8c5257b3fc.png)

Some discussion boards fail to display when the extension is installed. 

For me, in my CS 1200 class, it fails to display, but it works in my ECS 1100 class.

**Comment by ez314** [comment]
Can you post a screenshot of what the page looks like with the extension turned off?
You can do this by toggling the button in the extension popout window and reloading.

**Comment by GaganBhat** [comment]
Ah, sorry, it appears my professor closed the discussion topic today. It's working as expected, nothing exists on the tab. 
Maybe a small text that says that it's empty would help? Regardless, not a bug. 

![image](https://user-images.githubusercontent.com/25236969/100772253-fca1c980-33c4-11eb-8aa3-620fb5714403.png)
