### ISSUE TITLE
Only first of multiple attachments is displayed

### ISSUE THREAD

**Issue by ez314** [sunnyguan/whiteboard#31]
When an item has multiple attachments, only the first one is made available in Whiteboard

![image](https://user-images.githubusercontent.com/36653830/107064212-e3404380-67a0-11eb-924a-cd2e35afa0fb.png)

![image](https://user-images.githubusercontent.com/36653830/107064120-c9066580-67a0-11eb-8374-6ddc9115e056.png)

**Comment by sunnyguan** [comment]
Ah I think it's because the box is not wide enough to show all the attachments on the same line, I'll move them to separate lines then.
